src/Entity/Categories.php
<?php

namespace App\Entity;

use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoriesRepository::class)
 */
class Categories
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nom_categorie;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categorie_image;

    /**
     * @ORM\OneToMany(targetEntity=Produits::class, mappedBy="categories")
     */
    private $produits;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $desc_categorie;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }


    public function getCategorieImage(): ?string
    {
        return $this->categorie_image;
    }

    public function setCategorieImage(string $categorie_image): self
    {
        $this->categorie_image = $categorie_image;

        return $this;
    }

    /**
     * @return Collection|Produits[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produits $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setCategories($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getCategories() === $this) {
                $produit->setCategories(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->nom_categorie;
    }

    public function getDescCategorie(): ?string
    {
        return $this->desc_categorie;
    }

    public function setDescCategorie(string $desc_categorie): self
    {
        $this->desc_categorie = $desc_categorie;

        return $this;
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Categories;
use App\Entity\MailList;
use App\Form\MailListType;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(Request $request, EntityManagerInterface $em): Response
    {
        // ------------------------------------
        // -------------             CATEGORIES
        // ------------------------------------
        $cat_repository = $em->getRepository(Categories::class);
        $categories = $cat_repository->findSixLast();

        // ------------------------------------
        // -------------                 FOOTER
        // ------------------------------------
        // Creating email list form
        $email_list = new MailList();
        $email_form = $this->createForm(MailListType::class, $email_list);

        // handling request for email list form
        $email_form->handleRequest($request);
        if ($email_form->isSubmitted() && $email_form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($email_list);
            $entityManager->flush();
        }

        // ------------------------------------
        // -------------                 RENDER
        // ------------------------------------
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'email_form' => $email_form->createView(),
            'categories' => $categories,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre expert café fair trade & bio sourcé - café.com{% endblock %}

{% block body %}
    {# ----------------------- #}
    {# ---      HERO BANNER #}
    {# ----------------------- #}

    {# Hero Banner Style #}
    <link rel="stylesheet" href="{{ asset("assets/css/hero.css") }}" type="text/css">

    {# Hero Banner HTML #}
    <div id="hero-banner">
        <div id="hero-text">
            <h2>Découvrez un nouveau café exotique</h2>
            <p id="hero-description">L'arôme délicat de la noix de coco donne de la douceur au goût riche du café. Le
                duo exotique vous plongera
                dans l'atmosphère de vacances à la plage et vous transportera sur la côte paradisiaque.</p>
            <a href="#" class="hero-btn button-shadow">Voir la promotion</a>
        </div>
    </div>
    <div id="hero-banner-mobile">
        <h2>
            Les cafés du moment...
        </h2>
    </div>


    {# ----------------------- #}
    {# ---      CATEGORIES     #}
    {# ----------------------- #}

    {# Categories Style #}
    <link rel="stylesheet" href="{{ asset("assets/css/categories.css") }}" type="text/css">

    {# Categories HTML #}
    <div id="categorie-container">
        {% for categorie in categories %}
            <div class="category-card">
                <h2 class="cat-title">
                    {{ categorie.nomCategorie }}
                </h2>
                <p class="cat-description">
                    {{ categorie.descCategorie }}
                </p>
                <button class="cat-btn button-shadow">
                    Details
                </button>
                <img src="{{ asset(categorie.categorieImage) }}" alt="Image de description de la categorie : {{ categorie.nomCategorie }}" class="cat-img">
            </div>
        {% endfor %}
    </div>

    {# ----------------------- #}
    {# ---      APP    ------- #}
    {# ----------------------- #}

    {# App Styles #}
    <link rel="stylesheet" href="{{ asset("assets/css/app.css") }}" type="text/css">

    {# Font Awesome link #}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

    {# App Html #}
    <div id="App-container">

        {# first upper left text #}

        <div id="App-link">
            <div id="App-text">
                <h2 id="titre-h2">D&eacute;couvrez toutes les fonctionnalit&eacute;s de notre application !</h2>
                <p id="App-description">T&eacute;l&eacute;chargez-la vite et profites de 5% de remise suppl&eacute;mentaire sur
                    votre prochain achat.</p>
            </div>

            {# text Qr code and button#}

            <div id="App-button">

                {# Qr Code #}

                <div id="App-qrcode">
                    <a href='https://www.unitag.io/qrcode'>
                        <img src='https://www.unitag.io/qreator/generate?crs=Ppv8rOENN3V1lAwTz82zPpEYgrTpeQPpAxSJGcmyf1zqoOPAufHCjI4ccbj8leQIffpWitL50YSc%252FcPVAqhvQcY8L%252ByEXXE2GKn8SsxpZk4WZaQp7PKE7yfTgH2P3e9CKW00WL5%252F1cMS7FElOQtZuX8mpOG0vfXH1R11ooGrRdY%253D&crd=fhOysE0g3Bah%252BuqXA7NPQ87MoHrnzb%252BauJLKoOEbJsoOCuw%252BX4ighugFhTGaFhdwMowFnzz1VqZrff9HkhEKAQ%253D%253D' alt='QR Code'/>
                    </a>
                </div>

                <div id="App-column">

                    {# Grey text bottom #}

                    <div id="text-button">
                        <p id="grey-text">Visez le QR Code avec la cam&eacute;ra de votre smartphone et t&eacute;l&eacute;chargez l'application mobile gratuite.</p>
                    </div>

                    {# link icons and textlink #}

                    <div id="App-container-icons">
                        <div class="button-icons">
                            <i  class="fab fa-apple icons"></i>
                            <a class="icons" href="https://www.apple.com/fr/app-store/" target="_blank" title="app-store">Download on the<br><span class="icons-bold">App Store</span></a>
                        </div>
                        <div class="button-icons">
                            <i class="fab fa-google-play icons"></i>
                            <a class="icons" href="https://play.google.com/store?gl=FR"target="_blank" title="google-play">Get it on<br><span class="icons-bold">Google Play</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {# img smartphone right #}

        <div id="cafe_img">
            <img class="smartphone" src="/images/app/portable.png"  alt="img-portable">
        </div>
    </div>


{% endblock %}