src/Entity/Produits.php
<?php

namespace App\Entity;

use App\Repository\ProduitsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitsRepository::class)
 */
class Produits
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description_courte_produit;

    /**
     * @ORM\Column(type="text")
     */
    private $description_longue_produit;

    /**
     * @ORM\Column(type="decimal", precision=8, scale=2)
     */
    private $prix_achat_produit;

    /**
     * @ORM\Column(type="decimal", precision=8, scale=2)
     */
    private $prix_vente_produit;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock_disponible_produit;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock_alert_produit;

    /**
     * @ORM\Column(type="integer")
     */
    private $poids_g_produit;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categories;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescriptionCourteProduit(): ?string
    {
        return $this->description_courte_produit;
    }

    public function setDescriptionCourteProduit(string $description_courte_produit): self
    {
        $this->description_courte_produit = $description_courte_produit;

        return $this;
    }

    public function getDescriptionLongueProduit(): ?string
    {
        return $this->description_longue_produit;
    }

    public function setDescriptionLongueProduit(string $description_longue_produit): self
    {
        $this->description_longue_produit = $description_longue_produit;

        return $this;
    }

    public function getPrixAchatProduit(): ?string
    {
        return $this->prix_achat_produit;
    }

    public function setPrixAchatProduit(string $prix_achat_produit): self
    {
        $this->prix_achat_produit = $prix_achat_produit;

        return $this;
    }

    public function getPrixVenteProduit(): ?string
    {
        return $this->prix_vente_produit;
    }

    public function setPrixVenteProduit(string $prix_vente_produit): self
    {
        $this->prix_vente_produit = $prix_vente_produit;

        return $this;
    }

    public function getStockDisponibleProduit(): ?int
    {
        return $this->stock_disponible_produit;
    }

    public function setStockDisponibleProduit(int $stock_disponible_produit): self
    {
        $this->stock_disponible_produit = $stock_disponible_produit;

        return $this;
    }

    public function getStockAlertProduit(): ?int
    {
        return $this->stock_alert_produit;
    }

    public function setStockAlertProduit(int $stock_alert_produit): self
    {
        $this->stock_alert_produit = $stock_alert_produit;

        return $this;
    }

    public function getPoidsGProduit(): ?int
    {
        return $this->poids_g_produit;
    }

    public function setPoidsGProduit(int $poids_g_produit): self
    {
        $this->poids_g_produit = $poids_g_produit;

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    public function setCategories(Categories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

}

src/Form/ProduitsType.php
<?php

namespace App\Form;

use App\Entity\Produits;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description_courte_produit')
            ->add('description_longue_produit')
            ->add('prix_achat_produit')
            ->add('prix_vente_produit')
            ->add('stock_disponible_produit')
            ->add('stock_alert_produit')
            ->add('poids_g_produit')
            ->add('categories')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produits::class,
        ]);
    }
}

src/Controller/ProduitsController.php
<?php

namespace App\Controller;

use App\Entity\Produits;
use App\Form\ProduitsType;
use App\Repository\ProduitsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/produits")
 */
class ProduitsController extends AbstractController
{
    /**
     * @Route("/", name="produits_index", methods={"GET"})
     */
    public function index(ProduitsRepository $produitsRepository): Response
    {
        return $this->render('produits/index.html.twig', [
            'produits' => $produitsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="produits_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $produit = new Produits();
        $form = $this->createForm(ProduitsType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('produits_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produits/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="produits_show", methods={"GET"})
     */
    public function show(Produits $produit): Response
    {
        return $this->render('produits/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="produits_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Produits $produit): Response
    {
        $form = $this->createForm(ProduitsType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('produits_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produits/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="produits_delete", methods={"POST"})
     */
    public function delete(Request $request, Produits $produit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produits_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produits/_delete_form.html.twig
<form method="post" action="{{ path('produits_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produits/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produits/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produits{% endblock %}

{% block body %}
    <h1>Edit Produits</h1>

    {{ include('produits/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produits_index') }}">back to list</a>

    {{ include('produits/_delete_form.html.twig') }}
{% endblock %}

templates/produits/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits index{% endblock %}

{% block body %}
    <h1>Produits index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description_courte_produit</th>
                <th>Description_longue_produit</th>
                <th>Prix_achat_produit</th>
                <th>Prix_vente_produit</th>
                <th>Stock_disponible_produit</th>
                <th>Stock_alert_produit</th>
                <th>Poids_g_produit</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.descriptionCourteProduit }}</td>
                <td>{{ produit.descriptionLongueProduit }}</td>
                <td>{{ produit.prixAchatProduit }}</td>
                <td>{{ produit.prixVenteProduit }}</td>
                <td>{{ produit.stockDisponibleProduit }}</td>
                <td>{{ produit.stockAlertProduit }}</td>
                <td>{{ produit.poidsGProduit }}</td>
                <td>
                    <a href="{{ path('produits_show', {'id': produit.id}) }}">show</a>
                    <a href="{{ path('produits_edit', {'id': produit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('produits_new') }}">Create new</a>
{% endblock %}

templates/produits/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produits{% endblock %}

{% block body %}
    <h1>Create new Produits</h1>

    {{ include('produits/_form.html.twig') }}

    <a href="{{ path('produits_index') }}">back to list</a>
{% endblock %}

templates/produits/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits{% endblock %}

{% block body %}
    <h1>Produits</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Description_courte_produit</th>
                <td>{{ produit.descriptionCourteProduit }}</td>
            </tr>
            <tr>
                <th>Description_longue_produit</th>
                <td>{{ produit.descriptionLongueProduit }}</td>
            </tr>
            <tr>
                <th>Prix_achat_produit</th>
                <td>{{ produit.prixAchatProduit }}</td>
            </tr>
            <tr>
                <th>Prix_vente_produit</th>
                <td>{{ produit.prixVenteProduit }}</td>
            </tr>
            <tr>
                <th>Stock_disponible_produit</th>
                <td>{{ produit.stockDisponibleProduit }}</td>
            </tr>
            <tr>
                <th>Stock_alert_produit</th>
                <td>{{ produit.stockAlertProduit }}</td>
            </tr>
            <tr>
                <th>Poids_g_produit</th>
                <td>{{ produit.poidsGProduit }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('produits_index') }}">back to list</a>

    <a href="{{ path('produits_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produits/_delete_form.html.twig') }}
{% endblock %}